apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  db-url: "jdbc:postgresql://postgres-service:5432/vectordb"
  db-username: "postgres"
  db-password: "TwojeBezpieczneHaslo123!"
  mail-username: "PLACEHOLDER"
  mail-password: "PLACEHOLDER"
  google-client-id: "PLACEHOLDER"
  google-secret: "PLACEHOLDER"
  aws-access-key: "PLACEHOLDER"
  aws-secret-key: "PLACEHOLDER"
  anthropic-api-key: "PLACEHOLDER"
  google-access-key: "PLACEHOLDER"
  stripe-secret-key: "PLACEHOLDER"
