ALTER TABLE beautypg.course
    ADD COLUMN IF NOT EXISTS course_level   VARCHAR(20)  DEFAULT 'BEGINNER',
    ADD COLUMN IF NOT EXISTS status         VARCHAR(20)  DEFAULT 'PUBLISHED',
    ADD COLUMN IF NOT EXISTS language       VARCHAR(10)  DEFAULT 'pl',
    ADD COLUMN IF NOT EXISTS prerequisites  TEXT,
    ADD COLUMN IF NOT EXISTS learning_outcomes TEXT,
    ADD COLUMN IF NOT EXISTS certificate    BOOLEAN      DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS image_url      VARCHAR(500);
